// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nclzcublbysfvicmqzjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbHpjdWJsYnlzZnZpY21xempyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTA1MTIsImV4cCI6MjA2OTcyNjUxMn0.ltb_GOdC5koO6VNTtxtIC_UroKzFRl4KUzOg0vKPUws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});